duckdb:
  outputs:
    dev:
      type: duckdb
      path: "{{ env_var('JAFFLE_DB_PATH', 'jaffle_shop.duckdb') }}"
      threads: 4
      remote:
        host: 127.0.0.1
        port: 5433
        user: dbt
  target: dev
